### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by darrepac** [remisalmon/strava-local-heatmap#13]
Hi

I have the following error reading some GPX file. I guess one GPX could be corrupted but it could be good that the program is more robust and walk over:
**Reading activity_Afternoon_spring_walk_on_19_04_2021_22MWC2ctUdab3XyRBzGowTNJtTM.gpx
Reading activity_Afternoon_walk_in_the_☀️on_28_02_2021_22MR1PQbnlYKSLZy3ZatOHsNev7.gpx
Traceback (most recent call last):
  File "C:\temp\GPX\strava_local_heatmap.py", line 349, in <module>
    main(args)
  File "C:\temp\GPX\strava_local_heatmap.py", line 123, in main
    for line in file:
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 433: character maps to <undefined>**

**Comment by darrepac** [comment]
**with open(gpx_file, encoding='utf-8') as file:** seems to solve it
